Refactor/#179/토큰 재발급 리팩토링
mokInDang/project_backend pull request #187
Opened 2023-03-13 11:55 UTC by MinhoKK

# Refactor/#179/토큰 재발급 리팩토링

### 이슈 번호 : #179 

## 변경 사항
-    쿠키 생성 시 옵션 추가
      쿠키 만료 기한 60일 설정, 메인 도메인과 서브 도메인간 쿠키 송수신을 위해 sameSite("None")
-   @CookieValue 어노테이션 사용

## 그 외
- 

## 질문 사항
-

2023-03-13 14:57 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +                .sameSite("None")
찾아보니까 SameSite Enum 타입이 있네요!

2023-03-13 14:57 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +                .sameSite("None")
이 설정은 어떤 설정인간요?

2023-03-13 14:58 UTC, ch0ijihwan requested changes
리뷰 달았습니다 코멘트 확인해주세요~~

2023-03-14 03:10 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +                .sameSite("None")
PR 변경사항에 적어두었는데 '메인 도메인과 서브 도메인간 쿠키 송수신을 위해 sameSite("None")' 내용으로
서로 다른 도메인사이에서 쿠키를 송수신 할때 해당 옵션이 없으면 에러가 발생한다고 하여서 추가하였습니다!!

2023-03-14 04:06 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +                .sameSite("None")
Enum 타입으로 변경 되었나요?

2023-03-14 05:37 UTC, merged