Feature/#190/로그아웃 기능 구현
mokInDang/project_backend pull request #194
Opened 2023-03-15 14:49 UTC by MinhoKK

# Feature/#190/로그아웃 기능 구현

### 이슈 번호 : #190 

## 변경 사항
-    카카오계정 로그아웃 요청
-    DB에 refreshToken 삭제

## 그 외
- 

## 질문 사항
-

2023-03-16 14:50 UTC, ch0ijihwan requested changes

2023-03-16 14:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +        authenticationService.logout(memberId);
개인적으로 로깅 남기는게 좋을 것 같습니다!
다른 api 에서 다 로깅을 남겨서, 이것도 추가해주면 좋을 것 같아요

2023-03-16 14:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +        return ResponseEntity.noContent()
`noContent()`를 사용한 이유가 있을까요?

2023-03-16 14:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
> +
불필요한 개행이 있습니다

2023-03-16 14:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
> +                "https://kauth.kakao.com/oauth/logout?client_id=60b35611c843f6c8f618a495ecc8eaf6&logout_redirect_uri=https://www.dongnejupging.xyz/",
`client_id` 와 `redirect_url` 은 `yml`에 분리해서 사용하는 것이 좋을 것 같아요
아마 redirect_url 분리는 제가 이전에 해둔 내용이 있어서 그걸 쓰면 불필요한 코드 중복을 제거할 수 있을 것 같습니다.

2023-03-16 14:50 UTC, ch0ijihwan commented on src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
> +    @DisplayName("로그아웃 시 204 반환")
@DisplayName 은 구체적으로 작성하는 것이 좋아요
로그아웃 요청 시, HTTP 상태코드 204를 반환하고, 해당하는 리프레시 토큰을 제거한다 등으로 구체적으로 작성하는게 좋습니다.

2023-03-16 15:00 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +        authenticationService.logout(memberId);
로깅 추가 하겠습니다!

2023-03-16 15:01 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
> +        return ResponseEntity.noContent()
로그아웃 시 아무런 반환값이 없어 고민하다가 병주형 우테코 코드를 참고하였습니다..!

2023-03-16 15:02 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
> +
style 개행 제거 하겠습니다!

2023-03-16 15:15 UTC, MinhoKK commented on src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
> +    @DisplayName("로그아웃 시 204 반환")
실질적으로 refreshToken 삭제와 카카오 세션 만료 요청을 하는 부분이 AuthenticationService여서 
AuthenticationServiceTest의 @DisplayName에 해당 내용을 적었습니다.

위와같은 이유로 ControllerTest에 @DisplayName은 상태코드 반환만 적어도 된다고 생각했습니다..!

컨트롤러에도 좀더 정확하게 @DisplayName을 작성하겠습니다!!

2023-03-17 03:46 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
> +                "https://kauth.kakao.com/oauth/logout?client_id=60b35611c843f6c8f618a495ecc8eaf6&logout_redirect_uri=https://www.dongnejupging.xyz/",
저는 client_id가 외부에 노출되면 안되기에 git secret key로 등록하여 사용할 생각이었는데 secret key보다 yml에 분리하는 것이 더 좋은 방법일가요??

2023-03-17 04:13 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
> +                "https://kauth.kakao.com/oauth/logout?client_id=60b35611c843f6c8f618a495ecc8eaf6&logout_redirect_uri=https://www.dongnejupging.xyz/",
보안적으로 분리하여 관리하는게 좋을 것 같습니다.

2023-03-20 06:04 UTC, merged