Feature/#207/프로필 사진 저장,조회 기능 구현
mokInDang/project_backend pull request #222
Opened 2023-03-31 11:18 UTC by MinhoKK

# Feature/#207/프로필 사진 저장,조회 기능 구현

### 이슈 번호 : #207 

## 변경 사항
-    amazon S3 버킷으로 프로필 이미지 업로드
      업로드 시 기존 이미지는 삭제
      Member 엔티티에 ProfileImage vo 추가

## 그 외
- 

## 질문 사항
-

2023-03-31 11:48 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/domain/member/vo/ProfileImage.java
> +    }
createByNull 메소드는 메소드명을 못바꿨네요 createByDefault 이런식으로 후에 리팩토링 하겠습니다

2023-04-04 16:11 UTC, ch0ijihwan requested changes
리뷰 좀 많음~~ 보고 코멘트 달아주세요

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +@Slf4j
개인적으로 slf4j 주석을 최상단에 두는게 더 좋은 것 같습니다..!

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    @PostMapping("/upload")
`/upload` 보다는 url 에 자원을 명시하는게 더 좋을 것 같아요.
Post를 사용하니 동적인 의미는 전달 되었다고 생각합니다. 따라서 생성하는 자원을 명시하는게 더 restful 한 것 같습니다.

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    public ResponseEntity<FileResponse> uploadProfileImage(@Login Long memberId, @RequestPart(value = "file") MultipartFile multipartFile) {
`@RequestPart(value = "file") ` 이부분이 어떤 역할을 하는건가요?

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +
이런 서비스적인 로직은 Service 레이어에서 처리하는게 맞다고 생각이 듭니다.
또한 File 처리를 하는 Service 를 해당 컨트롤러에서 의존하는 것이 아닌, 
memberService 내부에서 갖고있는게 맞다는 생각이 들어요.

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        }
이 부분 private 메서드로 분리해서 처리하는게 가독성 측면에서 더 좋을 것 같습니다!
uploadFile 메서드 내부 로직이 복잡하다고 느껴집니다.

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +
이미지 업로드를 위해서 사전 작업을 하는 부분이라고 생각됩니다. 이 부분도 메서드로 분리하는게 좋을 것 같습니다!

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFileUrl = "";
이 부분은 파일 url 이 없어서 `""` 상태로 두신건가요?

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
파일 경로를 "profile_image" 라고 하신 이유가 궁금합니다.

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +
불필요한 개행 제거

2023-04-04 16:11 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
상단에 같은 이름의 변수를 사용합니다. 이런 중복은 가독성을 떨어트린다고 생각해요!
필드로 따로 뽑아두는게 좋을 것 같습니다.

2023-04-05 04:52 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    public ResponseEntity<FileResponse> uploadProfileImage(@Login Long memberId, @RequestPart(value = "file") MultipartFile multipartFile) {
![ex](https://user-images.githubusercontent.com/101318473/229984068-cf21da93-5770-456d-a39d-dbd59a188bd8.PNG)

2023-04-05 04:53 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    public ResponseEntity<FileResponse> uploadProfileImage(@Login Long memberId, @RequestPart(value = "file") MultipartFile multipartFile) {
위와같이 첨부파일 형식으로 PNG파일은 'form-data'로 넘어오고 이때 Key값이 file로 'value'에 해당하는 값이고 첨부파일을 받을때 사용하는 어노테이션이 '@RequestPart' 입니다

2023-04-05 05:00 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
![bu](https://user-images.githubusercontent.com/101318473/229985147-89b0641b-abb3-40e6-aa3d-18a316defe33.PNG)

2023-04-05 05:00 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
버킷 내부에 프로필 이미지들이 저장될 디렉토리 이름이어서 이와같이 했습니다.

2023-04-05 05:09 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    @PostMapping("/upload")
`/upload/image` 이처럼 자원을 명시하는 것을 말해주신거죠??

2023-04-05 05:11 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        }
if문을 제외한 코드는 블로그를 참고한 후 response dto만 수정하고 내부 로직을 리팩토링하지 않아서 복잡하게 느껴진 것 같습니다..!

메소드 분리 및 수정을 통해 리팩토링 해보겠습니다!

2023-04-05 05:11 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
반영완료!

2023-04-05 05:11 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +
반영완료!

2023-04-05 05:30 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +    @PostMapping("/upload")
post 자체가 업로드 의미가 들어가니 `/api/member/profile-image` 정도면 어떨가요?

2023-04-05 13:27 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFileUrl = "";
네 맞습니다! 초기화를 `""` 상태로 하고 값 선언이 try 내부에서 되고 return 해당 값이 return 됩니다

2023-04-05 13:37 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
> +
생각해보니 그렇게 하는게 맞는 방법같네요!

`memberService.updateProfileImage()`를 fileService.uploadFile() 내부에서 처리하도록 리팩토링 했습니다.

2023-04-05 13:37 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +
반영완료!

2023-04-05 13:38 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
> +        String uploadFilePath = "profile_image";
반영완료!

2023-04-05 15:08 UTC, ch0ijihwan approved these changes

2023-04-06 05:43 UTC, merged