Feature/#223 마이페이지 조회 구현
mokInDang/project_backend pull request #224
Opened 2023-04-01 05:36 UTC by MinhoKK

# Feature/#223 마이페이지 조회 구현

### 이슈 번호 : #223 

## 변경 사항
-    MyPageResponse Dto 구현
-    Member 엔티티에 ProfileImage vo 추가
-   이에 따른 테스트 코드 추가 및 수정

## 그 외
- 

## 질문 사항
-

2023-04-02 08:50 UTC, ch0ijihwan requested changes

2023-04-02 08:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/domain/member/vo/ProfileImage.java
> +    public static final String DEFAULT_PROFILE_IMAGE_NAME = "DEFAULT_PROFILE_IMAGE_NAME";
DEFAULT_PROFILE_IMAGE_URL 에 해당하는 URL 은 아직 없어서 이와같이 구현해두신걸까요?

2023-04-02 08:50 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/member/response/MyPageResponse.java
> +@Builder
빌더 쓰신이유가 있나요?

2023-04-04 06:54 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/domain/member/vo/ProfileImage.java
> +    public static final String DEFAULT_PROFILE_IMAGE_NAME = "DEFAULT_PROFILE_IMAGE_NAME";
맨처음에 멤버 생성시 해당 필드값으로 null을 부여하고 프론트에서 해당 값이 null이면 기본 이미지를 불러오도록 하자고 이야기 나와서 해당 필드에 null을 부여하려다 null을 직접 프론트에 넘기기보다 default값을 넣어서 반환하고 이후에 이미지 업로드하면 해당 필드값에 이미지 URL이 들어가도록 구현할 생각이었습니다

2023-04-04 06:54 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/member/response/MyPageResponse.java
> +@Builder
생성메서드를 구현하지 않고도 해당 객체를 생성할때 어떤 필드에 어떤 값이 부여되는지 확인 가능해서 사용했습니다..!

혹시 빌더를 사용하면 안되는걸가요??

2023-04-04 06:54 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
> +                .build();
해당 부분을 맨처음 빌더 없이 아래와 같이 구현했는데 해당 DTO가 어떤 필드를 가지고 있는지 가독성 좋게 보여줄려면 빌드를 사용하는 것도 좋은 방법일 수 있다고 생각해서 한번 사용해봤습니다.

return new MyPageResponse(member.getAlias(), member.getRegion().getValue(), member.getProfileImage().getProfileImageUrl());

2023-04-04 06:55 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/domain/member/vo/ProfileImage.java
> +    public static final String DEFAULT_PROFILE_IMAGE_NAME = "DEFAULT_PROFILE_IMAGE_NAME";
굳굳 좋은것 같습니다

2023-04-04 06:57 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
> +                .build();
저는 빌더패턴을 안써봐서 잘몰라서 질문드렸었습니다.
이때 찾아보니까 빌더패턴 단점이 가독성이 좋아진다고 하지만, 하나하나 필드를 넣어줘야하는 귀찮음이 생길 수 있다고도 하더군요!

DTO 가 어떤 필드를 가지고 있는지 가독성을 좋게한다? 라는 관점으로 봤을 때, 이정도는 생성자 방식으로 생성해도 괜찮을거 같다는 생각도 듭니다.

2023-04-04 06:57 UTC, ch0ijihwan commented on src/main/java/mokindang/jubging/project_backend/service/member/response/MyPageResponse.java
> +@Builder
사용하면 안되는게 아니라 궁금해서 물어봤습니다

2023-04-04 06:59 UTC, MinhoKK commented on src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
> +                .build();
넵! 생성자 생성으로 수정하고 머지하겠습니다!

2023-04-04 07:14 UTC, merged